# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_power_float)
add_subdirectory(ND_power_vector2)
add_subdirectory(ND_power_vector3)
add_subdirectory(ND_power_vector4)
add_subdirectory(ND_power_color3)
add_subdirectory(ND_power_color4)
add_subdirectory(ND_power_vector2FA)
add_subdirectory(ND_power_vector3FA)
add_subdirectory(ND_power_vector4FA)
add_subdirectory(ND_power_color3FA)
add_subdirectory(ND_power_color4FA)
