# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(add)
add_subdirectory(subtract)
add_subdirectory(multiply)
add_subdirectory(divide)
add_subdirectory(modulo)
add_subdirectory(power)
add_subdirectory(safepower)
add_subdirectory(min)
add_subdirectory(max)
add_subdirectory(atan2)
