# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_ifequal_color3)
add_subdirectory(ND_ifequal_color3B)
add_subdirectory(ND_ifequal_color3I)

add_subdirectory(ND_ifequal_color4)
add_subdirectory(ND_ifequal_color4B)
add_subdirectory(ND_ifequal_color4I)

add_subdirectory(ND_ifequal_float)
add_subdirectory(ND_ifequal_floatB)
add_subdirectory(ND_ifequal_floatI)

add_subdirectory(ND_ifequal_vector2)
add_subdirectory(ND_ifequal_vector2B)
add_subdirectory(ND_ifequal_vector2I)

add_subdirectory(ND_ifequal_vector3)
add_subdirectory(ND_ifequal_vector3B)
add_subdirectory(ND_ifequal_vector3I)

add_subdirectory(ND_ifequal_vector4)
add_subdirectory(ND_ifequal_vector4B)
add_subdirectory(ND_ifequal_vector4I)
