# Copyright 2025 DreamWorks Animation LLC
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(colorcorrect)
add_subdirectory(contrast)
add_subdirectory(hsvadjust)
add_subdirectory(hsvtorgb)
add_subdirectory(luminance)
add_subdirectory(range)
add_subdirectory(smoothstep)
add_subdirectory(remap)
add_subdirectory(rgbtohsv)
add_subdirectory(saturate)
