# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(adjustment)
add_subdirectory(application)
add_subdirectory(channel)
add_subdirectory(colortransform)
add_subdirectory(compositing)
add_subdirectory(conditional)
add_subdirectory(convolution2d)
add_subdirectory(geometric)
add_subdirectory(global)
add_subdirectory(math)
add_subdirectory(pbr)
add_subdirectory(procedural)
add_subdirectory(texture)
