# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(clamp)
add_subdirectory(crossproduct)
add_subdirectory(determinant)
add_subdirectory(distance)
add_subdirectory(dotproduct)
add_subdirectory(invert)
add_subdirectory(invertmatrix)
add_subdirectory(magnitude)
add_subdirectory(normalize)
add_subdirectory(normalmap)
add_subdirectory(one_operand)
add_subdirectory(place2d)
add_subdirectory(reflect)
add_subdirectory(refract)
add_subdirectory(rotate2d)
add_subdirectory(rotate3d)
add_subdirectory(swizzle)
add_subdirectory(transformmatrix)
add_subdirectory(transform)
add_subdirectory(transpose)
add_subdirectory(two_operands)
