# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_add_float)
add_subdirectory(ND_add_vector2)
add_subdirectory(ND_add_vector3)
add_subdirectory(ND_add_vector4)
add_subdirectory(ND_add_color3)
add_subdirectory(ND_add_color4)
add_subdirectory(ND_add_matrix33)
add_subdirectory(ND_add_matrix44)
add_subdirectory(ND_add_vector2FA)
add_subdirectory(ND_add_vector3FA)
add_subdirectory(ND_add_vector4FA)
add_subdirectory(ND_add_color3FA)
add_subdirectory(ND_add_color4FA)
add_subdirectory(ND_add_matrix33FA)
add_subdirectory(ND_add_matrix44FA)
