add_subdirectory(ND_fractal3d_color3)
add_subdirectory(ND_fractal3d_color3FA)
add_subdirectory(ND_fractal3d_color4)
add_subdirectory(ND_fractal3d_color4FA)
add_subdirectory(ND_fractal3d_float)
add_subdirectory(ND_fractal3d_vector2)
add_subdirectory(ND_fractal3d_vector2FA)
add_subdirectory(ND_fractal3d_vector3)
add_subdirectory(ND_fractal3d_vector3FA)
add_subdirectory(ND_fractal3d_vector4)
add_subdirectory(ND_fractal3d_vector4FA)
