# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_ifgreatereq_color3)
add_subdirectory(ND_ifgreatereq_color3I)

add_subdirectory(ND_ifgreatereq_color4)
add_subdirectory(ND_ifgreatereq_color4I)

add_subdirectory(ND_ifgreatereq_float)
add_subdirectory(ND_ifgreatereq_floatI)

add_subdirectory(ND_ifgreatereq_vector2)
add_subdirectory(ND_ifgreatereq_vector2I)

add_subdirectory(ND_ifgreatereq_vector3)
add_subdirectory(ND_ifgreatereq_vector3I)

add_subdirectory(ND_ifgreatereq_vector4)
add_subdirectory(ND_ifgreatereq_vector4I)
