# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(absval)
add_subdirectory(sign)
add_subdirectory(floor)
add_subdirectory(ceil)
add_subdirectory(round)
add_subdirectory(sin)
add_subdirectory(cos)
add_subdirectory(tan)
add_subdirectory(asin)
add_subdirectory(acos)
add_subdirectory(sqrt)
add_subdirectory(ln)
add_subdirectory(exp)
