# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_geompropvalue_boolean)
add_subdirectory(ND_geompropvalue_integer)
add_subdirectory(ND_geompropvalue_float)
add_subdirectory(ND_geompropvalue_color3)
add_subdirectory(ND_geompropvalue_color4)
#string output shaders aren't supported yet
#add_subdirectory(ND_geompropvalue_string)
add_subdirectory(ND_geompropvalue_vector2)
add_subdirectory(ND_geompropvalue_vector3)
add_subdirectory(ND_geompropvalue_vector4)
