# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_divide_float)
add_subdirectory(ND_divide_vector2)
add_subdirectory(ND_divide_vector3)
add_subdirectory(ND_divide_vector4)
add_subdirectory(ND_divide_color3)
add_subdirectory(ND_divide_color4)
add_subdirectory(ND_divide_matrix33)
add_subdirectory(ND_divide_matrix44)
add_subdirectory(ND_divide_vector2FA)
add_subdirectory(ND_divide_vector3FA)
add_subdirectory(ND_divide_vector4FA)
add_subdirectory(ND_divide_color3FA)
add_subdirectory(ND_divide_color4FA)
