# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(cellnoise2d)
add_subdirectory(cellnoise3d)
add_subdirectory(checkerboard)
add_subdirectory(circle)
add_subdirectory(cloverleaf)
add_subdirectory(constant)
add_subdirectory(crosshatch)
add_subdirectory(grid)
add_subdirectory(hexagon)
add_subdirectory(line)
add_subdirectory(noise2d)
add_subdirectory(noise3d)
add_subdirectory(fractal3d)
add_subdirectory(ramp4)
add_subdirectory(ramplr)
add_subdirectory(ramptb)
add_subdirectory(randomcolor)
add_subdirectory(randomfloat)
add_subdirectory(splitlr)
add_subdirectory(splittb)
add_subdirectory(tiledcloverleafs)
add_subdirectory(tiledhexagons)
add_subdirectory(tiledcircles)
add_subdirectory(trianglewave)
add_subdirectory(unifiednoise2d)
add_subdirectory(unifiednoise3d)
add_subdirectory(worleynoise2d)
add_subdirectory(worleynoise3d)
