# Copyright 2024 DreamWorks Animation LLC
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(TestBoolOutputMap)
add_subdirectory(TestIntOutputMap)
add_subdirectory(TestColorOutputMap)
add_subdirectory(TestVec4fOutputMap)
add_subdirectory(TestRgbaOutputMap)
add_subdirectory(TestMat3fOutputMap)
add_subdirectory(TestMat4fOutputMap)
add_subdirectory(TestInputsNormalMap)
add_subdirectory(TestInputsMap)
add_subdirectory(TestNormalMap2Map)
