# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_add)
add_subdirectory(ND_atan2)
add_subdirectory(ND_divide)
add_subdirectory(ND_max)
add_subdirectory(ND_min)
add_subdirectory(ND_modulo)
add_subdirectory(ND_multiply)
add_subdirectory(ND_power)
add_subdirectory(ND_safepower)
add_subdirectory(ND_subtract)
