# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_invert_float)
add_subdirectory(ND_invert_vector2)
add_subdirectory(ND_invert_vector3)
add_subdirectory(ND_invert_vector4)
add_subdirectory(ND_invert_color3)
add_subdirectory(ND_invert_color4)
add_subdirectory(ND_invert_vector2FA)
add_subdirectory(ND_invert_vector3FA)
add_subdirectory(ND_invert_vector4FA)
add_subdirectory(ND_invert_color3FA)
add_subdirectory(ND_invert_color4FA)
