# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Moonray Project

add_subdirectory(ND_max_float)
add_subdirectory(ND_max_vector2)
add_subdirectory(ND_max_vector3)
add_subdirectory(ND_max_vector4)
add_subdirectory(ND_max_color3)
add_subdirectory(ND_max_color4)
add_subdirectory(ND_max_vector2FA)
add_subdirectory(ND_max_vector3FA)
add_subdirectory(ND_max_vector4FA)
add_subdirectory(ND_max_color3FA)
add_subdirectory(ND_max_color4FA)
